# app/web/Dockerfile
FROM nginx:alpine
LABEL maintainer="your-name@example.com"
# remove default nginx content
RUN rm -rf /usr/share/nginx/html/*
# Copy website files
COPY . /usr/share/nginx/html
# Expose port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
